# Generated by Django 5.0.2 on 2024-02-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_article_image_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='article_images/', verbose_name='makaleye fotoğraf ekleyin'),
        ),
    ]
